---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: charliegen@hotmail.se
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: traefik
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv
  labels:
    app: cv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cv
  template:
    metadata:
      labels:
        app: cv
    spec:
      containers:
      - name: cv
        image: ghcr.io/kaese72/cv:v0.0.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cv
  labels:
    app: cv
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: cv
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: cv
  labels:
    app: cv
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: cv.kaese.space
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: cv
              port:
                number: 80
  tls:
  - hosts:
    - cv.kaese.space
    secretName: letsencrypt-prod
